# Generated by Django 2.2 on 2019-04-18 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stations',
            fields=[
                ('station_no', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Trains',
            fields=[
                ('train_no', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Schedules',
            fields=[
                ('schedule_no', models.AutoField(primary_key=True, serialize=False)),
                ('departure_time', models.DateField()),
                ('landing_time', models.DateField()),
                ('arrival_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrival_station', to='core.Stations')),
                ('departure_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departure_station', to='core.Stations')),
                ('train_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Trains')),
            ],
        ),
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('booking_no', models.AutoField(primary_key=True, serialize=False)),
                ('passenger_name', models.CharField(max_length=100)),
                ('passenger_age', models.IntegerField()),
                ('passenger_contact', models.IntegerField()),
                ('passenger_email', models.CharField(max_length=100)),
                ('seat_count', models.IntegerField()),
                ('schedule_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Schedules')),
            ],
        ),
    ]
