# Generated by Django 2.2 on 2019-04-18 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedules',
            name='landing_time',
        ),
        migrations.AddField(
            model_name='schedules',
            name='arrival_time',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='schedules',
            name='fare',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='schedules',
            name='departure_time',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
