# Generated by Django 2.2 on 2019-04-18 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190418_0215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedules',
            name='arrival_time',
            field=models.TimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='schedules',
            name='departure_time',
            field=models.TimeField(blank=True, default=None, null=True),
        ),
    ]
